export const PROJECT_NAME = "scriptss";
export const NAME_REGEX = /^[\d:A-Za-z]+$/;
export const NAMESPACES = [
	"build",
	"dev",
	"format",
	"other",
	"report",
	"setup",
	"start",
	"test",
];
export const DEFAULT_HOOKS = [
	"install",
	"postinstall",
	"postpack",
	"postpublish",
	"postrestart",
	"postshrinkwrap",
	"poststart",
	"poststop",
	"posttest",
	"postuninstall",
	"postversion",
	"preinstall",
	"prepack",
	"prepare",
	"prepublish",
	"prepublishOnly",
	"prerestart",
	"preshrinkwrap",
	"prestart",
	"prestop",
	"pretest",
	"preuninstall",
	"preversion",
	"publish",
	"restart",
	"shrinkwrap",
	"stop",
	"uninstall",
	"version",
];
